language: php

# run tests on php misc php versions supported by eZ Publish 5.1 and up
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

# test only master (+ Pull requests)
branches:
  only:
    - master

# install dependencies
install: composer install --dev --prefer-dist

# execute phpunit as the script command
script:
  - php vendor/bin/phpunit -d memory_limit=-1 --colors

# disable mail notifications
notification:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
